image: haskell:8.6.5 

stages:
  - build
  - test

cache:
  key: purty-v1
  paths:
    - .stack-root
    - .stack-work

variables:
  LC_ALL: C.UTF-8
  STACK_ROOT: $CI_PROJECT_DIR/.stack-root

build-linux:
  stage: build
  needs: []
  script:
    - stack build --copy-bins --local-bin-path ./artifacts --flag purepur:static 
  artifacts:
    paths:
      - ./artifacts

build-macos:
  stage: build
  tags: [macOS]
  needs: []
  script:
    - stack build --copy-bins --local-bin-path ./artifacts --flag purepur:static
  artifacts:
    paths:
      - ./artifacts



test:
  stage: test
  needs: []
  script:
    - stack build --test --no-run-tests --flag purepur:static --haddock --no-haddock-deps
