image: haskell:8.6.5 

cache:
  key: purty-v1
  paths:
    - .stack-root
    - .stack-work

variables:
  LC_ALL: C.UTF-8
  STACK_ROOT: $CI_PROJECT_DIR/.stack-root

build:
  script:
    - stack build --copy-bins --flag purepur:static 
  artifacts:
    paths:
      - /root/.local/bin/purepur

test:
  script:
    - stack build --test --no-run-tests --flag purepur:static --haddock --no-haddock-deps
